/*********************************************************************
Name:  PEM_Constants
Copyright © 2016  Salesforce
=====================================================================

Purpose: Set of list of Contants used by PEM

=====================================================================
History
-------
VERSION  AUTHOR            DATE         DETAIL                      Description
 1.0    Simon Coles        2016-11-16   Initial version
*********************************************************************/

public with sharing class PEM_Constants {

	// Used in UserTrigger Handler when selecting a picklist.
	public static String ccsOrgSector = 'Central Government';
	public static String ccsPlusLicense = 'CCS Community Plus User';

}